{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFrameWork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginButton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickLoginButton2()\n        self.gt.verifyWrongCredential()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:39: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <AppiumFrameWork.pages.LoginPage.LoginPage object at 0x000001C0EBC63F70>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle, \"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:47: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1698995691465, "stop": 1698995691465}, {"name": "Click on Login Button", "status": "passed", "start": 1698995692112, "stop": 1698995692112}, {"name": "Entered email id", "status": "passed", "start": 1698995693649, "stop": 1698995693649}, {"name": "Entered Password", "status": "passed", "start": 1698995694718, "stop": 1698995694718}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1698995695777, "stop": 1698995695777}, {"name": "Wrong Credentials Handling Successfull", "status": "passed", "start": 1698995695827, "stop": 1698995695827}], "attachments": [{"name": "text", "source": "5588309d-0102-4a0b-99e9-1c8c71a259b1-attachment.png", "type": "image/png"}, {"name": "log", "source": "13b9b387-c380-4461-9fad-9d6f2f02b25f-attachment.txt", "type": "text/plain"}], "start": 1698995691464, "stop": 1698995721894, "uuid": "0c36e812-ebb4-4761-8057-869e0b28c7cc", "historyId": "3a9d02cb75e772be1b1cb3cca9e22635", "testCaseId": "bd0ee788d71213cf83d440f83be52100", "fullName": "AppiumFrameWork.tests.LoginTest.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "parentSuite", "value": "AppiumFrameWork.tests"}, {"name": "suite", "value": "LoginTest"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "DESKTOP-1E9OV05"}, {"name": "thread", "value": "24160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "AppiumFrameWork.tests.LoginTest"}]}